### ISSUE TITLE
General TODO issue

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/black-renderer#3]
- [x] decide upon a license, and open the repo
- [x] set up ~fuzzy~ image compare, so we can compare with expected images ~(adapt from [drawbot-skia tests](https://github.com/justvanrossum/drawbot-skia/blob/f9d5314ee8cf99c9f11b58a914bd76728fe383af/tests/test_api.py#L203-L227))~
- [x] add support for COLRv0 and non-color fonts
- [x] figure out PaintComposite with blend modes
- [ ] make test font that covers more of the COLRv1 spec
- [x] make new `__main__` prog, that takes a string, a font, options, and outputs a rendered image
- [x] publish on PyPI

**Comment by drott** [comment]
> [ ] make test font that covers more of the COLRv1 spec

I've been using
https://github.com/googlefonts/color-fonts/blob/main/config/more_samples-glyf_colr_1.py
for my regression testing and added more exaples for skaling, skew, rotate, and recently ClipBoxes.

Feel free to contribute to that one.
